### ISSUE TITLE
What to do about scroll events?

### ISSUE THREAD

**Issue by RByers** [WICG/input-device-capabilities#5]
Scroll events don't technically represent a single input (eg. multiple devices may scroll the same element at the same time - what sourceDevice would we want then?).  Should we spec a particular behavior?  Should we have any tests?

**Comment by tdresser** [comment]
I'm trying to come up with a scenario where using the `InputDevice` from the most recent cause of scrolling wouldn't work. I haven't come up with anything.

If we can go with an approach with that level of complexity, I think specifying the behavior would be worthwhile.

**Comment by RByers** [comment]
It might be a bit of a pain for us to implement correctly in chromium.  We might need to extend all the scrolling machinery with some source tracking, eg. to reliably know when a wheel event actually changed an offset (as opposed to just attempted to scroll but couldn't).  This would involve some plumbing from CC to blink (since there are cases today when CC scrolls and blink has no idea why) and some conflict resolution when blink and cc have registered scrolls for different reasons.

I'm OK saying this is the desired behavior though, but not necessarily blocking shipping sourceDevice in chromium on fixing it.

**Comment by RByers** [comment]
Ah ha, the UI Events spec is changing to align with CSSOM View definition where scroll is just an 'Event': https://code.google.com/p/chromium/issues/detail?id=503280.  So this is not an issue ATM.  We might want to expose a sourceDevice on scroll in the future but the value seems low compared to the cost (maybe best addressed by scroll customization anyway).
